/* Auto-generated by scripts/match-odds.mjs — do not edit by hand.
   Per-match Polymarket odds (90-min result), last snapshot while the market
   was open. m: {matchId: {h,d,a,t}} — probabilities 0..1; id = "HC-AC" for
   group games, "K<matchNumber>" (73..104) for knockout games. */
const MATCH_ODDS = {"updated":"2026-07-06T19:10:37.667Z","m":{"K94":{"h":0.385,"d":0.275,"a":0.345,"t":"2026-07-06T19:10:37.666Z"},"K93":{"h":0.255,"d":0.275,"a":0.465,"t":"2026-07-06T19:10:37.666Z"},"K95":{"h":0.715,"d":0.205,"a":0.085,"t":"2026-07-06T19:10:37.666Z"},"K96":{"h":0.265,"d":0.315,"a":0.425,"t":"2026-07-06T19:10:37.666Z"},"K97":{"h":0.615,"d":0.245,"a":0.145,"t":"2026-07-06T19:10:37.667Z"},"K99":{"h":0.235,"d":0.265,"a":0.515,"t":"2026-07-06T19:10:37.667Z"}}};
