/* Auto-generated by scripts/match-odds.mjs — do not edit by hand.
   Per-match Polymarket odds (90-min result), last snapshot while the market
   was open. m: {matchId: {h,d,a,t}} — probabilities 0..1; id = "HC-AC" for
   group games, "K<matchNumber>" (73..104) for knockout games. */
const MATCH_ODDS = {"updated":"2026-07-07T08:46:41.706Z","m":{"K94":{"h":0.105,"d":0.225,"a":0.665,"t":"2026-07-07T01:11:33.641Z"},"K93":{"h":0.255,"d":0.275,"a":0.465,"t":"2026-07-06T19:10:37.666Z"},"K95":{"h":0.725,"d":0.195,"a":0.085,"t":"2026-07-07T08:46:41.705Z"},"K96":{"h":0.265,"d":0.315,"a":0.425,"t":"2026-07-07T08:46:41.705Z"},"K97":{"h":0.615,"d":0.245,"a":0.145,"t":"2026-07-07T08:46:41.706Z"},"K99":{"h":0.235,"d":0.265,"a":0.515,"t":"2026-07-07T08:46:41.706Z"}}};
