/* Auto-generated by scripts/match-odds.mjs — do not edit by hand.
   Per-match Polymarket odds (90-min result), last snapshot while the market
   was open. m: {matchId: {h,d,a,t}} — probabilities 0..1; id = "HC-AC" for
   group games, "K<matchNumber>" (73..104) for knockout games. */
const MATCH_ODDS = {"updated":"2026-07-08T20:40:42.889Z","m":{"K94":{"h":0.105,"d":0.225,"a":0.665,"t":"2026-07-07T01:11:33.641Z"},"K93":{"h":0.255,"d":0.275,"a":0.465,"t":"2026-07-06T19:10:37.666Z"},"K95":{"h":0.265,"d":0.365,"a":0.385,"t":"2026-07-07T17:31:07.649Z"},"K96":{"h":0.255,"d":0.355,"a":0.395,"t":"2026-07-07T20:18:31.109Z"},"K97":{"h":0.625,"d":0.245,"a":0.135,"t":"2026-07-08T20:40:42.889Z"},"K99":{"h":0.225,"d":0.265,"a":0.525,"t":"2026-07-08T20:40:42.889Z"},"K98":{"h":0.605,"d":0.245,"a":0.165,"t":"2026-07-08T20:40:42.889Z"},"K100":{"h":0.565,"d":0.275,"a":0.165,"t":"2026-07-08T20:40:42.889Z"}}};
