// Polymarket "World Cup Winner" team name → our 3-letter code, plus a helper to
// fetch the event. Shared by the daily snapshot job and the one-time backfill.
export const CODES = {
  "Mexico":"MEX","South Africa":"RSA","South Korea":"KOR","Korea Republic":"KOR","Czechia":"CZE","Czech Republic":"CZE",
  "Canada":"CAN","Bosnia and Herzegovina":"BIH","Bosnia & Herzegovina":"BIH","Bosnia-Herzegovina":"BIH","Qatar":"QAT","Switzerland":"SUI",
  "Brazil":"BRA","Morocco":"MAR","Haiti":"HAI","Scotland":"SCO",
  "United States":"USA","USA":"USA","Paraguay":"PAR","Australia":"AUS","Turkey":"TUR","Turkiye":"TUR","Türkiye":"TUR",
  "Germany":"GER","Curacao":"CUW","Curaçao":"CUW","Cote d'Ivoire":"CIV","Ivory Coast":"CIV","Côte d'Ivoire":"CIV","Ecuador":"ECU",
  "Netherlands":"NED","Japan":"JPN","Sweden":"SWE","Tunisia":"TUN",
  "Belgium":"BEL","Egypt":"EGY","Iran":"IRN","New Zealand":"NZL",
  "Spain":"ESP","Cape Verde":"CPV","Cabo Verde":"CPV","Saudi Arabia":"KSA","Uruguay":"URU",
  "France":"FRA","Senegal":"SEN","Iraq":"IRQ","Norway":"NOR",
  "Argentina":"ARG","Algeria":"ALG","Austria":"AUT","Jordan":"JOR",
  "Portugal":"POR","DR Congo":"COD","Congo DR":"COD","Uzbekistan":"UZB","Colombia":"COL",
  "England":"ENG","Croatia":"CRO","Ghana":"GHA","Panama":"PAN",
};

export async function fetchWorldCupEvent(){
  const r = await fetch("https://gamma-api.polymarket.com/events?slug=world-cup-winner",
    { headers: { "User-Agent": "wc26-hub-snapshot/1.0" } });
  if(!r.ok) throw new Error("gamma http "+r.status);
  const d = await r.json();
  return Array.isArray(d) ? d[0] : d;
}

import { writeFileSync } from "node:fs";
// Persist the owned archive as both machine-readable JSON and a browser-loadable
// JS global (so the chart works with no fetch — even after the market closes).
export function saveHistory(hist){
  const root = new URL("../", import.meta.url);
  const json = JSON.stringify(hist);
  writeFileSync(new URL("history.json", root), json + "\n");
  writeFileSync(new URL("history.js", root),
    "/* Auto-generated by .github/workflows/odds-snapshot.yml — do not edit by hand.\n" +
    "   Owned daily archive of Polymarket win-probabilities; lets the chart render\n" +
    "   forever, even after the market closes. snapshots: [{date, p:{CODE: yesPrice}}]. */\n" +
    "const HISTORY = " + json + ";\n");
}
