// Event-indexed win-probability archive: instead of one snapshot per calendar day
// (history.js), this samples each team's Polymarket price at the moment each match
// FINISHES. Every slot therefore carries maximum information — a bar per discrete
// result, not per arbitrary day — and dodges the timezone/midnight ambiguity of the
// daily view. Emits EVENT_HISTORY for the hero chart (two-level phase·date axis) and
// the per-team "road to the title" chart on team pages.
//
// Source: Polymarket prices-history (fidelity=60 ⇒ hourly tape) sampled at each
// match-completion timestamp derived from the committed schedule (FIX/MATCHES/KNOCKOUT).
// Owned + committed, like history.js — renders forever with zero runtime fetch.
import { readFileSync, writeFileSync } from "node:fs";
import { CODES, fetchWorldCupEvent } from "./codes.mjs";

const GROUP_DUR = 2 * 3600;     // kickoff → final whistle (incl. half-time + stoppage)
const KO_DUR    = 2.5 * 3600;   // knockouts can run to extra time + penalties
const ROOT = new URL("../", import.meta.url);

// --- 1. The schedule is a browser global (no ESM exports); evaluate it in a sandbox.
const src = readFileSync(new URL("schedule.js", ROOT), "utf8");
const { FIX, MATCHES, KNOCKOUT } = new Function(src + "\n;return {FIX, MATCHES, KNOCKOUT};")();

// --- 2. Resolve a Polymarket CLOB token per team.
const ev = await fetchWorldCupEvent();
const tokens = {};
for(const m of ev.markets || []){
  const code = CODES[(m.groupItemTitle || "").trim()];
  if(!code) continue;
  try { tokens[code] = JSON.parse(m.clobTokenIds)[0]; } catch {}
}
const teamCodes = Object.keys(tokens);
if(teamCodes.length < 30){ console.error("only", teamCodes.length, "teams resolved — aborting"); process.exit(1); }

// --- 3. Pull each team's hourly price tape (oldest→newest).
const tape = {};
for(const c of teamCodes){
  try {
    const r = await fetch(`https://clob.polymarket.com/prices-history?market=${tokens[c]}&interval=all&fidelity=60`);
    const h = (await r.json()).history || [];
    tape[c] = h.map(pt => [pt.t, Math.round((+pt.p) * 1e4) / 1e4]).sort((a, b) => a[0] - b[0]);
  } catch(e){ tape[c] = []; console.error("skip", c, String(e)); }
  await new Promise(r => setTimeout(r, 120));   // be gentle on the API
}
// price of team c as of unix time t = last tape point at or before t (null if none yet)
const priceAt = (c, t) => { let v = null; for(const [pt, pp] of (tape[c] || [])){ if(pt <= t) v = pp; else break; } return v; };

// --- 4. Build the match list: completed group games + resolved knockout games.
const NOW = Math.floor(Date.now() / 1000);
const ku = ts => Math.floor(new Date(ts).getTime() / 1000);   // ISO → unix sec
const matches = [];
for(const m of MATCHES){
  const [hc, ac, hs, as, status] = m;
  if(status !== "fin") continue;                      // only matches that have a result
  const fx = FIX[`${hc}-${ac}`];
  if(!fx) continue;                                   // no kickoff time on record
  const kick = ku(fx[0]);
  matches.push({ kick, done: kick + GROUP_DUR, phase: "Group stage", hc, ac, hs, as });
}
for(const k of KNOCKOUT){
  if(!k.hc || !k.ac || k.hs == null || k.as == null) continue;   // unresolved / not played
  const kick = ku(k.utc);
  matches.push({ kick, done: kick + KO_DUR, phase: k.round, hc: k.hc, ac: k.ac, hs: k.hs, as: k.as });
}

// --- 5. Merge matches that finish together into one slot (e.g. simultaneous final
//        group games), keep only finished slots, order by completion time.
const byDone = new Map();
for(const m of matches){
  if(m.done > NOW) continue;
  const key = String(m.done);
  if(!byDone.has(key)) byDone.set(key, { done: m.done, kick: m.kick, phase: m.phase, matches: [] });
  byDone.get(key).matches.push({ hc: m.hc, ac: m.ac, hs: m.hs, as: m.as });
}
const slots = [...byDone.values()].sort((a, b) => a.done - b.done).map(s => {
  const p = {};
  for(const c of teamCodes){ const v = priceAt(c, s.done); if(v != null) p[c] = v; }
  return {
    t: new Date(s.done * 1000).toISOString(),       // completion timestamp (anchor)
    utc: new Date(s.kick * 1000).toISOString(),     // kickoff
    phase: s.phase,
    matches: s.matches,
    p,
  };
});

// --- 6. Persist owned archive (JSON + browser global), mirroring saveHistory().
const out = { updated: new Date().toISOString(), slots };
const json = JSON.stringify(out);
writeFileSync(new URL("event-history.json", ROOT), json + "\n");
writeFileSync(new URL("event-history.js", ROOT),
  "/* Auto-generated by scripts/event-history.mjs — do not edit by hand.\n" +
  "   Win-probabilities sampled at each match's final whistle. One slot per result.\n" +
  "   slots: [{t, utc, phase, matches:[{hc,ac,hs,as}], p:{CODE: winProb}}]. */\n" +
  "const EVENT_HISTORY = " + json + ";\n");
console.log("event-history:", slots.length, "slots,", teamCodes.length, "teams ·",
  slots.length ? slots[0].t.slice(0, 10) + " → " + slots.at(-1).t.slice(0, 10) : "(none yet)");
