#!/usr/bin/env python3
# Extract each team's two main FLAG colours → flag-colors.js, for the "Tartan (flag)"
# bar-colour mode. Done at build time from real flag images (flagcdn.com) rather than
# from the flag emoji in the browser, because Windows renders flag emoji as plain
# "ES"/"FR" text — client-side sampling would be garbage there. Mirrors the JS crest
# extraction (coarse RGB quantise → two most frequent, sufficiently-different colours).
#
# FLAG_COLOR = { CODE: [{h,s,l}, {h,s,l}] }  (h in degrees, s/l in 0..1 — same shape as CREST_COLOR)
import io, re, json, colorsys, urllib.request
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
HTML = (ROOT / "index.html").read_text(encoding="utf-8")

# Teams whose flag isn't a 2-letter regional-indicator emoji → explicit flagcdn slug.
OVERRIDE = {"ENG": "gb-eng", "SCO": "gb-sct", "WAL": "gb-wls"}

def slug(code, emoji):
    if code in OVERRIDE:
        return OVERRIDE[code]
    ri = [ord(ch) for ch in emoji if 0x1F1E6 <= ord(ch) <= 0x1F1FF]   # regional indicators → ISO-3166-1 alpha-2
    if len(ri) >= 2:
        return chr(ri[0] - 0x1F1E6 + 97) + chr(ri[1] - 0x1F1E6 + 97)
    return None

def two_main_colors(img):
    img = img.convert("RGBA").resize((64, 42))
    buckets = {}
    for (r, g, b, a) in img.getdata():
        if a < 128:
            continue
        q = (min(255, round(r/64)*64), min(255, round(g/64)*64), min(255, round(b/64)*64))
        o = buckets.setdefault(q, [0, 0, 0, 0]); o[0]+=r; o[1]+=g; o[2]+=b; o[3]+=1
    arr = sorted(([o[0]/o[3], o[1]/o[3], o[2]/o[3], o[3]] for o in buckets.values()), key=lambda c: -c[3])
    if not arr:
        return []
    out = [arr[0]]
    for c in arr[1:]:
        if abs(c[0]-out[0][0]) + abs(c[1]-out[0][1]) + abs(c[2]-out[0][2]) > 90:   # sufficiently different
            out.append(c); break
    def to_hsl(c):
        h, l, s = colorsys.rgb_to_hls(c[0]/255, c[1]/255, c[2]/255)
        return {"h": round(h*360, 1), "s": round(s, 3), "l": round(l, 3)}
    return [to_hsl(c) for c in out]

# Parse the baked team table: CODE:["Name","<emoji>","Group","Conf"]
teams = re.findall(r'\b([A-Z]{3}):\["([^"]*)","([^"]*)","[^"]*","[^"]*"\]', HTML)
seen, FLAG = set(), {}
for code, name, emoji in teams:
    if code in seen:
        continue
    seen.add(code)
    s = slug(code, emoji)
    if not s:
        print("no slug for", code, name); continue
    try:
        req = urllib.request.Request(f"https://flagcdn.com/w320/{s}.png", headers={"User-Agent": "wc26-hub/1.0"})
        img = Image.open(io.BytesIO(urllib.request.urlopen(req, timeout=20).read()))
        FLAG[code] = two_main_colors(img)
    except Exception as e:
        print("skip", code, s, e)

assert len(FLAG) >= 44, f"only {len(FLAG)} flags resolved"
out = json.dumps(FLAG, separators=(",", ":"))
(ROOT / "flag-colors.json").write_text(out + "\n")
(ROOT / "flag-colors.js").write_text(
    "/* Auto-generated by scripts/flag-colors.py — do not edit by hand.\n"
    "   Each team's two main FLAG colours (flagcdn.com), for the 'Tartan (flag)' mode.\n"
    "   FLAG_COLOR = { CODE: [{h,s,l}, {h,s,l}] }. */\n"
    "const FLAG_COLOR = " + out + ";\n", encoding="utf-8")
print("flag-colors:", len(FLAG), "teams")
