// Per-match win/draw/win odds from Polymarket's match markets (series
// "soccer-fifwc"). Each World Cup game gets an event like
// fifwc-prt-esp-2026-07-06 carrying three Yes/No markets: home win, draw,
// away win (90-minute result). We snapshot the current prices for every OPEN
// event, matched to our schedule by kickoff time + team names, and merge them
// into an owned archive: a closed event keeps its last open-market snapshot
// (the final pre/mid-match odds) instead of collapsing to resolved 0/1.
//
// Match ids (shared with index.html): group games "HC-AC" (the FIX key),
// knockout games "K<matchNumber>" with number = 73 + index into KNOCKOUT.
// Emits MATCH_ODDS = {updated, m:{id:{h,d,a,t}}} — probabilities 0..1.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { CODES } from "./codes.mjs";

const SERIES_ID = 11433;   // gamma series "soccer-fifwc" — all WC-2026 match events
const ROOT = new URL("../", import.meta.url);

// --- 1. Schedule (browser globals) → the list of odds-addressable matches.
const src = readFileSync(new URL("schedule.js", ROOT), "utf8");
const { FIX, MATCHES, KNOCKOUT } = new Function(src + "\n;return {FIX, MATCHES, KNOCKOUT};")();
const wanted = [];   // {id, utc, hc, ac}
for(const [hc, ac] of MATCHES){
  const fx = FIX[`${hc}-${ac}`];
  if(fx && fx[0]) wanted.push({ id: `${hc}-${ac}`, utc: fx[0], hc, ac });
}
KNOCKOUT.forEach((k, i) => {
  if(k.hc && k.ac && k.utc) wanted.push({ id: `K${73 + i}`, utc: k.utc, hc: k.hc, ac: k.ac });
});

// --- 2. All OPEN match events in the series (base events only, no -exact-score etc).
const BASE_SLUG = /^fifwc-[a-z0-9]+-[a-z0-9]+-\d{4}-\d{2}-\d{2}$/;
async function openEvents(){
  const out = [];
  for(let offset = 0; ; offset += 100){
    const r = await fetch(`https://gamma-api.polymarket.com/events?series_id=${SERIES_ID}&closed=false&limit=100&offset=${offset}`,
      { headers: { "User-Agent": "wc26-hub-snapshot/1.0" } });
    if(!r.ok) throw new Error("gamma http " + r.status);
    const page = await r.json();
    out.push(...page);
    if(page.length < 100) break;
  }
  return out.filter(e => BASE_SLUG.test(e.slug || ""));
}

// --- 3. Extract {code: winProb} + draw from an event's three Yes/No markets.
function eventOdds(ev){
  const odds = { teams: {}, draw: null };
  for(const m of ev.markets || []){
    let p; try { p = JSON.parse(m.outcomePrices)[0]; } catch { continue; }
    if(p == null) continue;
    const title = (m.groupItemTitle || "").trim();
    if(/^draw\b/i.test(title)) odds.draw = +p;
    else if(CODES[title] != null) odds.teams[CODES[title]] = +p;
  }
  return odds;
}

// --- 4. Merge fresh snapshots over the existing archive.
const prevPath = new URL("match-odds.json", ROOT);
const prev = existsSync(prevPath) ? JSON.parse(readFileSync(prevPath, "utf8")) : { m: {} };
const m = prev.m || {};
const events = await openEvents();
let matched = 0;
for(const ev of events){
  const kick = Date.parse(ev.startTime || ev.startDate || "");
  if(!kick) continue;
  const o = eventOdds(ev);
  const hit = wanted.find(w => Date.parse(w.utc) === kick && o.teams[w.hc] != null && o.teams[w.ac] != null);
  if(!hit) continue;
  const r4 = v => v == null ? null : Math.round(v * 1e4) / 1e4;
  m[hit.id] = { h: r4(o.teams[hit.hc]), d: r4(o.draw), a: r4(o.teams[hit.ac]), t: new Date().toISOString() };
  matched++;
}

// --- 5. Persist (JSON + browser global), mirroring the other owned archives.
const out = { updated: new Date().toISOString(), m };
const json = JSON.stringify(out);
writeFileSync(prevPath, json + "\n");
writeFileSync(new URL("match-odds.js", ROOT),
  "/* Auto-generated by scripts/match-odds.mjs — do not edit by hand.\n" +
  "   Per-match Polymarket odds (90-min result), last snapshot while the market\n" +
  "   was open. m: {matchId: {h,d,a,t}} — probabilities 0..1; id = \"HC-AC\" for\n" +
  "   group games, \"K<matchNumber>\" (73..104) for knockout games. */\n" +
  "const MATCH_ODDS = " + json + ";\n");
console.log("match-odds:", events.length, "open events,", matched, "matched,", Object.keys(m).length, "archived");
