// Hourly win-probability tape for the hero stacked-area chart. Polymarket exposes
// an hourly price history (fidelity=60); this resamples it onto a regular hourly
// grid from the tournament's first kickoff to now, forward-filled, so the area
// renders as a smooth continuous evolution. Owned + committed, like history.js.
//
// ODDS_HOURLY = { updated, times:[ISO,…], p:{ CODE:[winProb,…aligned to times] } }
import { writeFileSync } from "node:fs";
import { CODES, fetchWorldCupEvent } from "./codes.mjs";

const FROM_ISO = "2026-06-11T00:00:00Z";   // tournament start; the visible x-window begins here
const STEP = 3600;                         // 1-hour grid
const ROOT = new URL("../", import.meta.url);

const ev = await fetchWorldCupEvent();
const tokens = {};
for(const m of ev.markets || []){
  const code = CODES[(m.groupItemTitle || "").trim()];
  if(!code) continue;
  try { tokens[code] = JSON.parse(m.clobTokenIds)[0]; } catch {}
}
const codes = Object.keys(tokens);
if(codes.length < 30){ console.error("only", codes.length, "teams resolved — aborting"); process.exit(1); }

const tape = {};
for(const c of codes){
  try {
    const r = await fetch(`https://clob.polymarket.com/prices-history?market=${tokens[c]}&interval=all&fidelity=60`);
    const h = (await r.json()).history || [];
    tape[c] = h.map(pt => [pt.t, Math.round((+pt.p) * 1e4) / 1e4]).sort((a, b) => a[0] - b[0]);
  } catch(e){ tape[c] = []; console.error("skip", c, String(e)); }
  await new Promise(r => setTimeout(r, 120));
}

const start = Math.floor(Date.parse(FROM_ISO) / 1000);
const lastT = Math.max(start, ...codes.map(c => tape[c].length ? tape[c].at(-1)[0] : start));
const grid = []; for(let t = start; t <= lastT; t += STEP) grid.push(t);

const p = {};
for(const c of codes){
  const arr = tape[c], out = new Array(grid.length).fill(0); let idx = 0, last = 0;
  for(let i = 0; i < grid.length; i++){ while(idx < arr.length && arr[idx][0] <= grid[i]){ last = arr[idx][1]; idx++; } out[i] = last; }
  p[c] = out;
}
const times = grid.map(t => new Date(t * 1000).toISOString());

const out = { updated: new Date().toISOString(), times, p };
const json = JSON.stringify(out);
writeFileSync(new URL("odds-hourly.json", ROOT), json + "\n");
writeFileSync(new URL("odds-hourly.js", ROOT),
  "/* Auto-generated by scripts/odds-hourly.mjs — do not edit by hand.\n" +
  "   Hourly Polymarket win-probabilities for the hero stacked-area chart.\n" +
  "   ODDS_HOURLY = { updated, times:[ISO,…], p:{CODE:[winProb,…]} }. */\n" +
  "const ODDS_HOURLY = " + json + ";\n");
console.log("odds-hourly:", times.length, "hourly points,", codes.length, "teams ·",
  times.length ? times[0].slice(0, 13) + "Z → " + times.at(-1).slice(0, 13) + "Z" : "(none)");
