// Resolve a photo for each squad player. Uses the EXACT Wikipedia article titles
// linked from the "2026 FIFA World Cup squads" page (so disambiguated players like
// "Name (footballer)" resolve correctly), then batch-queries page images (50/req).
// Writes player-img.js = const PLAYER_IMG { "<code>-<num>": "<thumbUrl>" }.
// Wikimedia Commons, CC-licensed; hotlinked. Re-runnable.

import { writeFileSync } from "node:fs";

const TEAMCODE = {
  "Czech Republic":"CZE","Mexico":"MEX","South Africa":"RSA","South Korea":"KOR","Bosnia and Herzegovina":"BIH",
  "Canada":"CAN","Qatar":"QAT","Switzerland":"SUI","Brazil":"BRA","Haiti":"HAI","Morocco":"MAR","Scotland":"SCO",
  "Australia":"AUS","Paraguay":"PAR","Turkey":"TUR","United States":"USA","Curaçao":"CUW","Ecuador":"ECU","Germany":"GER",
  "Ivory Coast":"CIV","Japan":"JPN","Netherlands":"NED","Sweden":"SWE","Tunisia":"TUN","Belgium":"BEL","Egypt":"EGY",
  "Iran":"IRN","New Zealand":"NZL","Cape Verde":"CPV","Saudi Arabia":"KSA","Spain":"ESP","Uruguay":"URU","France":"FRA",
  "Iraq":"IRQ","Norway":"NOR","Senegal":"SEN","Algeria":"ALG","Argentina":"ARG","Austria":"AUT","Jordan":"JOR",
  "Colombia":"COL","DR Congo":"COD","Portugal":"POR","Uzbekistan":"UZB","Croatia":"CRO","England":"ENG","Ghana":"GHA","Panama":"PAN",
};

// 1) Parse the squads wikitext for each player's (code, shirt#) -> Wikipedia article title.
const wt = await (await fetch("https://en.wikipedia.org/w/index.php?title=2026_FIFA_World_Cup_squads&action=raw",
  { headers:{ "User-Agent":"wc26-hub-photos/1.0 (personal project)" } })).text();
const idToTitle = {};
let code = null;
for(const line of wt.split("\n")){
  const h = /^===\s*(.+?)\s*===$/.exec(line);
  if(h){ code = TEAMCODE[h[1].trim()] || null; continue; }
  if(code && line.includes("{{nat fs g player")){
    const no = /\|no=(\d+)/.exec(line);
    const nm = /\|name=\[\[([^\]|]+)/.exec(line);   // article target before | or ]
    if(no && nm) idToTitle[code + "-" + (+no[1])] = nm[1].trim().replace(/_/g," ");
  }
}
const ids = Object.keys(idToTitle);
console.error("players with a wiki link:", ids.length);

// 2) Batch-query page images by exact title (follow redirects).
const titles = [...new Set(Object.values(idToTitle))];
const norm = s => s.replace(/_/g," ").trim();
const sleep = ms => new Promise(s=>setTimeout(s,ms));
const titleToImg = {};
const CHUNK = 50;
async function getJSON(url){ for(let a=0;a<6;a++){ try{ const r=await fetch(url,{headers:{ "User-Agent":"wc26-hub-photos/1.0 (personal project)" }}); if(!r.ok){ await sleep(900*(a+1)); continue; } return await r.json(); }catch(e){ await sleep(900*(a+1)); } } return null; }
async function resolve(list){
  for(let i=0;i<list.length;i+=CHUNK){
    const url = "https://en.wikipedia.org/w/api.php?action=query&format=json&origin=*&redirects=1"
      + "&prop=pageimages&piprop=thumbnail&pithumbsize=500&titles=" + encodeURIComponent(list.slice(i,i+CHUNK).join("|"));
    const data = await getJSON(url);
    if(!data || !data.query){ console.error("batch fail", i); await sleep(2000); continue; }
    const q = data.query, reroute = {};
    for(const n of (q.normalized||[])) reroute[norm(n.from)] = n.to;
    for(const rd of (q.redirects||[])) reroute[norm(rd.from)] = rd.to;
    const byTitle = {};
    for(const id in (q.pages||{})){ const p = q.pages[id]; if(p.thumbnail) byTitle[p.title] = p.thumbnail.source; }
    for(const t of list.slice(i,i+CHUNK)){
      const src = byTitle[reroute[norm(t)] || t] || byTitle[t];
      if(src) titleToImg[t] = src;   // use Wikipedia's exact thumb URL (rewriting the size 400s)
    }
    await sleep(450);   // be gentle / avoid throttling
  }
}
await resolve(titles);
let missing = titles.filter(t=>!titleToImg[t]);
console.error(`pass 1: ${Object.keys(titleToImg).length}/${titles.length} · retrying ${missing.length}`);
await resolve(missing);    // second pass recovers throttled batches
missing = titles.filter(t=>!titleToImg[t]);
console.error(`pass 2: ${Object.keys(titleToImg).length}/${titles.length} · retrying ${missing.length}`);
await resolve(missing);    // third pass for stragglers
console.error(`pass 3: ${Object.keys(titleToImg).length}/${titles.length}`);

// 3) Map back to player ids.
const IMG = {};
for(const id of ids){ const src = titleToImg[idToTitle[id]]; if(src) IMG[id] = src; }

writeFileSync(new URL("../player-img.js", import.meta.url),
  "/* Auto-generated by scripts/player-photos.mjs — player headshots resolved from\n" +
  "   Wikipedia (Wikimedia Commons, CC-licensed) via the squads' article links.\n" +
  "   Keyed by \"<code>-<shirtNumber>\". Partial coverage; UI falls back to the flag. */\n" +
  "const PLAYER_IMG = " + JSON.stringify(IMG) + ";\n");
console.error("done · " + Object.keys(IMG).length + "/1248 (" + Math.round(Object.keys(IMG).length/1248*100) + "%)");
